# Generated by Django 5.2.16 on 2026-08-18 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='AppZone', max_length=100)),
                ('primary_color', models.CharField(default='#5B2A9E', max_length=7)),
                ('min_password_length', models.PositiveIntegerField(default=8)),
                ('require_password_complexity', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
