# Generated by Django 5.2.16 on 2026-08-04 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(choices=[('github', 'GitHub'), ('azure_devops', 'Azure DevOps'), ('sql_server', 'SQL Server'), ('vpn', 'VPN'), ('internal_apis', 'Internal APIs'), ('test_environment', 'Test Environment'), ('other', 'Other')], max_length=20)),
                ('resource_other_label', models.CharField(blank=True, max_length=100)),
                ('access_level', models.CharField(blank=True, max_length=100)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequestStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_log', to='access_request.accessrequest')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
