# Generated by Django 5.2.16 on 2026-07-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
    ]
